version: '3.7'

services:
    db:
        container_name: postgres-glowspot
        image: postgis/postgis:latest # ✅ Образ с PostGIS
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DATABASE} # Было POSTGRES_DATABASE, исправлено на POSTGRES_DB
        ports:
            - 5433:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - glowspot-backend

    redis:
        container_name: redis-glowspot
        image: redis:5.0
        restart: always
        ports:
            - 6379:6379
        command: redis-server --requirepass ${REDIS_PASSWORD}
        volumes:
            - redis_data:/data
        networks:
            - glowspot-backend

volumes:
    postgres_data:
    redis_data:

networks:
    glowspot-backend:
